# /environment.yml
name: fastapi_project
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - fastapi==0.111.0
    - uvicorn[standard]==0.29.0
    - sqlalchemy==2.0.30
    - pydantic[email]==2.7.1
    - pydantic-settings==2.3.0
    - python-jose[cryptography]==3.3.0
    - passlib[bcrypt]==1.7.4
    - mysql-connector-python==8.4.0
    - python-multipart==0.0.9